<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYGM4tN3\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYGM4tN3/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerYGM4tN3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerYGM4tN3\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerYGM4tN3\srcApp_KernelProdContainer([
    'container.build_hash' => 'YGM4tN3',
    'container.build_id' => '76f6a005',
    'container.build_time' => 1571175544,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYGM4tN3');
