<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Controller\\EcoleHomeController::home'], [], [['text', '/home']], [], []],
    'classes' => [[], ['_controller' => 'App\\Controller\\EcoleHomeController::classes'], [], [['text', '/home/classes']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'security_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/deconnexion']], [], []],
];
