<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.B0M2Kjq' shared service.

return $this->privates['.service_locator.B0M2Kjq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EcoleHomeController::newClass' => ['privates', '.service_locator.GDtE0BI', 'get_ServiceLocator_GDtE0BIService.php', true],
    'App\\Controller\\EcoleHomeController::newStudent' => ['privates', '.service_locator._H1cT3m', 'get_ServiceLocator_H1cT3mService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\EcoleHomeController:newClass' => ['privates', '.service_locator.GDtE0BI', 'get_ServiceLocator_GDtE0BIService.php', true],
    'App\\Controller\\EcoleHomeController:newStudent' => ['privates', '.service_locator._H1cT3m', 'get_ServiceLocator_H1cT3mService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
], [
    'App\\Controller\\EcoleHomeController::newClass' => '?',
    'App\\Controller\\EcoleHomeController::newStudent' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\EcoleHomeController:newClass' => '?',
    'App\\Controller\\EcoleHomeController:newStudent' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
