<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.VFcEnU6' shared service.

return $this->privates['.service_locator.VFcEnU6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\EcoleHomeController::newClass' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\EcoleHomeController::newStudent' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
    'App\\Controller\\EcoleHomeController:newClass' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\EcoleHomeController:newStudent' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.oHXyyai', 'get_ServiceLocator_OHXyyaiService.php', true],
], [
    'App\\Controller\\EcoleHomeController::newClass' => '?',
    'App\\Controller\\EcoleHomeController::newStudent' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\EcoleHomeController:newClass' => '?',
    'App\\Controller\\EcoleHomeController:newStudent' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
