<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNfxIWb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNfxIWb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNfxIWb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNfxIWb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXNfxIWb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XNfxIWb',
    'container.build_id' => 'bd387074',
    'container.build_time' => 1577142487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNfxIWb');
