<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOn5nZWZ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOn5nZWZ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOn5nZWZ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOn5nZWZ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerOn5nZWZ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'On5nZWZ',
    'container.build_id' => 'd73a34d7',
    'container.build_time' => 1572307340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOn5nZWZ');
